### ISSUE TITLE
this.labels = this.factory.DefaultLabelAlphabet();空指针

### ISSUE THREAD

**Issue by dawsonjiang** [FudanNLP/fnlp#56]
CNFactory factory = CNFactory.getInstance("models");执行这句话就抛异常，文件目录没错

Exception in thread "main" java.lang.NullPointerException
	at org.fnlp.nlp.cn.tag.AbstractTagger.<init>(AbstractTagger.java:79)
	at org.fnlp.nlp.cn.tag.CWSTagger.<init>(CWSTagger.java:75)
	at org.fnlp.nlp.cn.CNFactory.loadSeg(CNFactory.java:219)
	at org.fnlp.nlp.cn.CNFactory.getInstance(CNFactory.java:164)
	at org.fnlp.nlp.cn.CNFactory.getInstance(CNFactory.java:144)

**Comment by dawsonjiang** [comment]
我也是这个错，兄台解决了么
