### ISSUE TITLE
跑测试程序失败

### ISSUE THREAD

**Issue by BenXu86** [FudanNLP/fnlp#58]
当运行如下代码时，发生错误：
```
	CNFactory factory = CNFactory.getInstance("models");
	HashMap<String, String> result = factory.ner("詹姆斯·默多克和丽贝卡·布鲁克斯 鲁珀特·默多克旗下的美国小报《纽约邮报》的职员被公司律师告知，保存任何也许与电话窃听及贿赂有关的文件。");

	 	// 显示标注结果
	System.out.println(result);
```
报如下错误：
```
Exception in thread "main" java.lang.NoClassDefFoundError: gnu/trove/map/hash/TCharCharHashMap
	at org.fnlp.nlp.cn.ChineseTrans.ensureST(ChineseTrans.java:54)
	at org.fnlp.nlp.cn.ChineseTrans.<init>(ChineseTrans.java:48)
	at org.fnlp.nlp.cn.CNFactory.<clinit>(CNFactory.java:54)
	at Test.main(Test.java:9)
Caused by: java.lang.ClassNotFoundException: gnu.trove.map.hash.TCharCharHashMap
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 4 more
```
我在您给的链接上下载的trove，但并没有TCharCharHashMap这个类。\
请问，这个问题怎么解决？

**Comment by BenXu86** [comment]
解决了，导入的jar包应该是trove-3.0.3.jar而不是trove-3.0.3-src.jar

**Comment by ps360pa** [comment]
您好，models文件夹下没有seg.m 以及pos.m这两个文件，请问该如何解决
